export const cryptoMarketData = {
  defi: [
    {
      id: "UNI/USD",
      symbol: "UNI",
      name: "Uniswap",
      value: 8.42,
      change: 0.34,
      pctChange: 4.21,
      volume: "142.5M",
      marketCap: "5.1B",
      time: "10:46",
      category: "DEX",
    },
    {
      id: "AAVE/USD",
      symbol: "AAVE",
      name: "Aave",
      value: 142.67,
      change: -2.15,
      pctChange: -1.48,
      volume: "89.2M",
      marketCap: "2.1B",
      time: "10:45",
      category: "Lending",
    },
    {
      id: "COMP/USD",
      symbol: "COMP",
      name: "Compound",
      value: 67.89,
      change: 1.23,
      pctChange: 1.85,
      volume: "45.7M",
      marketCap: "1.2B",
      time: "10:44",
      category: "Lending",
    },
    {
      id: "SUSHI/USD",
      symbol: "SUSHI",
      name: "SushiSwap",
      value: 1.34,
      change: 0.08,
      pctChange: 6.35,
      volume: "67.3M",
      marketCap: "172M",
      time: "10:43",
      category: "DEX",
    },
    {
      id: "CRV/USD",
      symbol: "CRV",
      name: "Curve DAO",
      value: 0.89,
      change: -0.05,
      pctChange: -5.32,
      volume: "34.1M",
      marketCap: "456M",
      time: "10:42",
      category: "DEX",
    },
  ],
  meme: [
    {
      id: "DOGE/USD",
      symbol: "DOGE",
      name: "Dogecoin",
      value: 0.0847,
      change: 0.0023,
      pctChange: 2.79,
      volume: "892.1M",
      marketCap: "12.1B",
      time: "10:46",
      category: "Meme",
    },
    {
      id: "SHIB/USD",
      symbol: "SHIB",
      name: "Shiba Inu",
      value: 0.00001234,
      change: -0.00000087,
      pctChange: -6.58,
      volume: "234.5M",
      marketCap: "7.3B",
      time: "10:45",
      category: "Meme",
    },
    {
      id: "PEPE/USD",
      symbol: "PEPE",
      name: "Pepe",
      value: 0.00000789,
      change: 0.00000156,
      pctChange: 24.67,
      volume: "567.8M",
      marketCap: "3.2B",
      time: "10:44",
      category: "Meme",
    },
    {
      id: "FLOKI/USD",
      symbol: "FLOKI",
      name: "Floki Inu",
      value: 0.000234,
      change: 0.000012,
      pctChange: 5.41,
      volume: "123.4M",
      marketCap: "2.1B",
      time: "10:43",
      category: "Meme",
    },
  ],
  layer1: [
    {
      id: "BTC/USD",
      symbol: "BTC",
      name: "Bitcoin",
      value: 67234.56,
      change: 1234.78,
      pctChange: 1.87,
      volume: "28.9B",
      marketCap: "1.3T",
      time: "10:46",
      category: "Store of Value",
    },
    {
      id: "ETH/USD",
      symbol: "ETH",
      name: "Ethereum",
      value: 3456.78,
      change: -89.23,
      pctChange: -2.52,
      volume: "15.2B",
      marketCap: "415B",
      time: "10:46",
      category: "Smart Contract",
    },
    {
      id: "SOL/USD",
      symbol: "SOL",
      name: "Solana",
      value: 189.45,
      change: 12.67,
      pctChange: 7.17,
      volume: "3.4B",
      marketCap: "89B",
      time: "10:45",
      category: "Smart Contract",
    },
    {
      id: "ADA/USD",
      symbol: "ADA",
      name: "Cardano",
      value: 0.4567,
      change: 0.0234,
      pctChange: 5.41,
      volume: "567M",
      marketCap: "16B",
      time: "10:44",
      category: "Smart Contract",
    },
    {
      id: "AVAX/USD",
      symbol: "AVAX",
      name: "Avalanche",
      value: 34.56,
      change: -1.23,
      pctChange: -3.44,
      volume: "234M",
      marketCap: "13B",
      time: "10:43",
      category: "Smart Contract",
    },
  ],
  ai: [
    {
      id: "FET/USD",
      symbol: "FET",
      name: "Fetch.ai",
      value: 1.234,
      change: 0.089,
      pctChange: 7.78,
      volume: "89.2M",
      marketCap: "1.1B",
      time: "10:46",
      category: "AI Agent",
    },
    {
      id: "OCEAN/USD",
      symbol: "OCEAN",
      name: "Ocean Protocol",
      value: 0.567,
      change: -0.034,
      pctChange: -5.66,
      volume: "45.7M",
      marketCap: "321M",
      time: "10:45",
      category: "Data",
    },
    {
      id: "RNDR/USD",
      symbol: "RNDR",
      name: "Render Token",
      value: 7.89,
      change: 0.45,
      pctChange: 6.05,
      volume: "123.4M",
      marketCap: "2.9B",
      time: "10:44",
      category: "Computing",
    },
    {
      id: "TAO/USD",
      symbol: "TAO",
      name: "Bittensor",
      value: 456.78,
      change: 23.45,
      pctChange: 5.41,
      volume: "67.8M",
      marketCap: "3.4B",
      time: "10:43",
      category: "AI Network",
    },
  ],
}
